"""baseline schema

Revision ID: 9a7f36609dac
Revises: 
Create Date: 2026-08-07 04:10:07.012230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a7f36609dac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_revoked'), ['revoked'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_event_ts', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('discovered_endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path_normalized', sa.String(length=1024), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_endpoints_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_endpoints_method'), ['method'], unique=False)
        batch_op.create_index('uq_disc_method_path', ['method', 'path_normalized'], unique=True, mysql_length={'path_normalized': 191})

    op.create_table('known_endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path_template', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_traffic_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'path_template', name='uq_known_method_path')
    )
    with op.batch_alter_table('known_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_endpoints_last_traffic_at'), ['last_traffic_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_endpoints_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_endpoints_path_template'), ['path_template'], unique=False)

    op.create_table('ml_model_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sklearn_version', sa.String(length=32), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openapi_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    # Mirrors the with_variant in app/models.py: LONGTEXT on MySQL (the
    # production DDL is unchanged), plain TEXT on other dialects so this
    # migration is also runnable against SQLite for local dev / e2e setup.
    sa.Column('raw_yaml', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_used'), ['used'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_user_used', ['user_id', 'used'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_refresh_user_revoked', ['user_id', 'revoked'], unique=False)

    op.create_table('shadow_endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path_normalized', sa.String(length=1024), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('sample_ips', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_reason', sa.String(length=512), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shadow_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shadow_endpoints_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_endpoints_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_endpoints_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_endpoints_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index('ix_shadow_method_path', ['method', 'path_normalized'], unique=True, mysql_length={'path_normalized': 191})
        batch_op.create_index('ix_shadow_risk', ['risk_score', 'hit_count'], unique=False)

    op.create_table('traffic_daily_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path_normalized', sa.String(length=1024), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_daily_summary', schema=None) as batch_op:
        batch_op.create_index('ix_summary_day', ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_daily_summary_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_daily_summary_method'), ['method'], unique=False)
        batch_op.create_index('uq_summary_day_method_path', ['day', 'method', 'path_normalized'], unique=True, mysql_length={'path_normalized': 191})

    op.create_table('traffic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('x_forwarded_for', sa.String(length=256), nullable=True),
    sa.Column('referer', sa.String(length=512), nullable=True),
    sa.Column('auth_present', sa.Boolean(), nullable=False),
    sa.Column('body_bytes', sa.Integer(), nullable=False),
    sa.Column('request_size_bytes', sa.Integer(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('monitor_key', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=256), nullable=True),
    sa.Column('raw_ref', sa.String(length=256), nullable=True),
    sa.Column('is_documented', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_events', schema=None) as batch_op:
        batch_op.create_index('ix_traffic_doc_ts', ['is_documented', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_monitor_key'), ['monitor_key'], unique=False)
        batch_op.create_index('ix_traffic_events_path', ['path'], unique=False, mysql_length=191)
        batch_op.create_index(batch_op.f('ix_traffic_events_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_traffic_method_path_ts', ['method', 'path', 'ts'], unique=False, mysql_length={'path': 191})

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('zombie_endpoint_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path_template', sa.String(length=512), nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('requests_7d', sa.Integer(), nullable=False),
    sa.Column('requests_14d', sa.Integer(), nullable=False),
    sa.Column('requests_30d', sa.Integer(), nullable=False),
    sa.Column('avg_daily_requests_30d', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('retire_reason', sa.String(length=512), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'path_template', name='uq_zombie_method_path')
    )
    with op.batch_alter_table('zombie_endpoint_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zombie_endpoint_state_last_request_at'), ['last_request_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zombie_endpoint_state_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_zombie_endpoint_state_path_template'), ['path_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_zombie_endpoint_state_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_zombie_endpoint_state_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zombie_endpoint_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zombie_endpoint_state_status'))
        batch_op.drop_index(batch_op.f('ix_zombie_endpoint_state_risk_level'))
        batch_op.drop_index(batch_op.f('ix_zombie_endpoint_state_path_template'))
        batch_op.drop_index(batch_op.f('ix_zombie_endpoint_state_method'))
        batch_op.drop_index(batch_op.f('ix_zombie_endpoint_state_last_request_at'))

    op.drop_table('zombie_endpoint_state')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('traffic_events', schema=None) as batch_op:
        batch_op.drop_index('ix_traffic_method_path_ts', mysql_length={'path': 191})
        batch_op.drop_index(batch_op.f('ix_traffic_events_ts'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_status_code'))
        batch_op.drop_index('ix_traffic_events_path', mysql_length=191)
        batch_op.drop_index(batch_op.f('ix_traffic_events_monitor_key'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_method'))
        batch_op.drop_index('ix_traffic_doc_ts')

    op.drop_table('traffic_events')
    with op.batch_alter_table('traffic_daily_summary', schema=None) as batch_op:
        batch_op.drop_index('uq_summary_day_method_path', mysql_length={'path_normalized': 191})
        batch_op.drop_index(batch_op.f('ix_traffic_daily_summary_method'))
        batch_op.drop_index(batch_op.f('ix_traffic_daily_summary_day'))
        batch_op.drop_index('ix_summary_day')

    op.drop_table('traffic_daily_summary')
    with op.batch_alter_table('shadow_endpoints', schema=None) as batch_op:
        batch_op.drop_index('ix_shadow_risk')
        batch_op.drop_index('ix_shadow_method_path', mysql_length={'path_normalized': 191})
        batch_op.drop_index(batch_op.f('ix_shadow_endpoints_risk_score'))
        batch_op.drop_index(batch_op.f('ix_shadow_endpoints_risk_level'))
        batch_op.drop_index(batch_op.f('ix_shadow_endpoints_method'))
        batch_op.drop_index(batch_op.f('ix_shadow_endpoints_last_seen'))

    op.drop_table('shadow_endpoints')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_user_revoked')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_revoked'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))
        batch_op.drop_index('ix_refresh_expires')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_user_used')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_used'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    op.drop_table('openapi_snapshots')
    op.drop_table('ml_model_state')
    with op.batch_alter_table('known_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_endpoints_path_template'))
        batch_op.drop_index(batch_op.f('ix_known_endpoints_method'))
        batch_op.drop_index(batch_op.f('ix_known_endpoints_last_traffic_at'))

    op.drop_table('known_endpoints')
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.drop_index('uq_disc_method_path', mysql_length={'path_normalized': 191})
        batch_op.drop_index(batch_op.f('ix_discovered_endpoints_method'))
        batch_op.drop_index(batch_op.f('ix_discovered_endpoints_last_seen'))

    op.drop_table('discovered_endpoints')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_success'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor'))
        batch_op.drop_index('ix_audit_event_ts')

    op.drop_table('audit_log')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_revoked'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
