"""ml model versioning and alert feedback

Revision ID: dbe6fa71ee42
Revises: 178fc3029731
Create Date: 2026-08-07 13:03:18.770943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe6fa71ee42'
down_revision: Union[str, Sequence[str], None] = '178fc3029731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('feedback_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_event_id'), ['event_id'], unique=False)

    # ml_model_state predates multi-tenancy (Phase 1): existing rows hold one
    # global model with no org_id. Same 3-step pattern as the org_id rollout
    # in 178fc3029731 (nullable -> backfill -> NOT NULL), so it's safe to run
    # against a populated production table. is_active/sample_count get a
    # server_default so existing rows are valid the instant the columns
    # exist — no separate backfill step needed for those two.
    with op.batch_alter_table('ml_model_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('sample_count', sa.Integer(), nullable=False, server_default='0'))

    bind = op.get_bind()
    default_org_id = bind.execute(
        sa.text("SELECT id FROM organizations ORDER BY id ASC LIMIT 1")
    ).scalar()
    if default_org_id is not None:
        # Any pre-multi-tenancy model becomes the (already-active) model for
        # the earliest org, so an upgrading deployment doesn't silently lose
        # its trained model — the next scheduled retrain re-splits it out
        # per org from there.
        bind.execute(
            sa.text("UPDATE ml_model_state SET org_id = :org_id WHERE org_id IS NULL"),
            {"org_id": default_org_id},
        )
    # else: no organizations exist yet (fresh install with no traffic ever
    # ingested) — ml_model_state is empty too, so there's nothing to backfill.

    with op.batch_alter_table('ml_model_state', schema=None) as batch_op:
        batch_op.alter_column('org_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index('ix_ml_model_org_active', ['org_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_state_org_id'), ['org_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_model_state_org_id'))
        batch_op.drop_index('ix_ml_model_org_active')
        batch_op.drop_column('sample_count')
        batch_op.drop_column('is_active')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_event_id'))
        batch_op.drop_column('feedback_at')
        batch_op.drop_column('feedback')
        batch_op.drop_column('explanation')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
