#!/usr/bin/env python3
"""Bootstrap a development .env file with securely generated random secrets.

Usage:
    python scripts/setup_dev_env.py            # generate only if missing
    python scripts/setup_dev_env.py --force    # overwrite with fresh secrets

Creates .env in the project root with cryptographically random values for
all required secrets.  If an .env already exists but is missing any required
secret (e.g. the template checked into the repo), the file is rewritten with
fresh values.  Use --force to rotate every secret regardless of state.
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

REQUIRED_KEYS = (
    "MYSQL_ROOT_PASSWORD",
    "MYSQL_PASSWORD",
    "SECRET_KEY",
    "MONITOR_API_KEY",
    "ADMIN_PASSWORD",
    "GRAFANA_ADMIN_PASSWORD",
    "DATABASE_URL",
)


def _random_password(length: int = 24) -> str:
    """Generate a URL-safe random password that satisfies the password policy."""
    while True:
        pw = secrets.token_urlsafe(length)
        if (
            any(c.isupper() for c in pw)
            and any(c.islower() for c in pw)
            and any(c.isdigit() for c in pw)
            and any(c in "-_" for c in pw)
            and len(pw) >= 16
        ):
            return pw


def _parse_existing_env(text: str) -> dict[str, str]:
    """Return {KEY: value} for every uncommented KEY=VALUE line in text."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and value:
            out[key] = value
    return out


def _needs_generation(env_path: Path) -> bool:
    """True when .env is missing or is missing any REQUIRED_KEYS value."""
    if not env_path.exists():
        return True
    existing = _parse_existing_env(env_path.read_text(encoding="utf-8"))
    return any(k not in existing for k in REQUIRED_KEYS)


def generate_env() -> str:
    """Return the full .env file content with generated secrets."""
    mysql_root_pw = _random_password()
    mysql_pw = _random_password()
    secret_key = secrets.token_hex(32)
    monitor_key = secrets.token_hex(32)
    admin_pw = _random_password()
    grafana_pw = _random_password()

    return f"""\
# ============================================================
#  API Security Monitor — auto-generated development environment
#  Generated by: scripts/setup_dev_env.py
#
#  NEVER commit this file. It is already in .gitignore.
# ============================================================

# ── MySQL ────────────────────────────────────────────────────
MYSQL_ROOT_PASSWORD={mysql_root_pw}
MYSQL_PASSWORD={mysql_pw}

# ── FastAPI application ──────────────────────────────────────
# Inside docker compose the API talks to the mysql service by name.
DATABASE_URL=mysql+pymysql://apimonitor:{mysql_pw}@mysql:3306/apimonitor
SECRET_KEY={secret_key}
MONITOR_API_KEY={monitor_key}

# Bootstrap admin
ADMIN_USERNAME=admin
ADMIN_PASSWORD={admin_pw}

# ── Grafana ──────────────────────────────────────────────────
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD={grafana_pw}

# ── Optional / defaulted ────────────────────────────────────
# Set APP_ENV=production to enforce strict secret validation at startup.
APP_ENV=development
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
CORS_ORIGINS=
ML_RETRAIN_MINUTES=15
IDLE_THRESHOLD_HOURS=24
"""


def main() -> int:
    force = "--force" in sys.argv

    if ENV_FILE.exists() and not force and not _needs_generation(ENV_FILE):
        print(f"OK: .env already exists at {ENV_FILE} and has all required secrets.")
        print("    Use --force to rotate every secret.")
        return 0

    content = generate_env()
    ENV_FILE.write_text(content, encoding="utf-8")
    try:
        os.chmod(ENV_FILE, 0o600)
    except OSError:
        pass  # Windows etc. — best effort

    print(f"OK: Generated {ENV_FILE} with fresh random secrets.")
    print()
    print("Next steps:")
    print("  docker compose up --build")
    print()
    print("Or for local development (without Docker for the API):")
    print("  docker compose up -d mysql prometheus grafana")
    print("  uvicorn app.main:app --reload --host 127.0.0.1 --port 8000")
    return 0


if __name__ == "__main__":
    sys.exit(main())
